version: '3.8'


services:
  dagster:
    build:
      context: dagster/
      dockerfile: Dockerfile
    volumes:
      - ./dagster:/opt/dagster/dagster_home
      - ./dbt_project:/opt/dagster/dbt_project
    env_file:
      - .env
    expose: 
      - 3000
    ports:
      - 3000:3000
    
  postgres:
    image: postgres:latest
    expose: 
      - 54322
    ports:
      - 54322:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DAGSTER_PG_PASSWORD}
      - POSTGRES_USER=${DAGSTER_PG_USERNAME}
      - POSTGRES_DB=${DAGSTER_PG_DB}
    volumes:
      - dagster-postgres:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabaseappdb
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=${METABASE_PASSWORD}
      - MB_DB_HOST=postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  meta-postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_DB=metabaseappdb
      - POSTGRES_PASSWORD=${METABASE_PASSWORD}
    networks:
      - metanet1
volumes:
  dagster-postgres:
    driver: local

